config/routes.rb
Rails.application.routes.draw do
  get '/index', to: 'app/front#index', as: :app_index
  root to: 'app/front#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  namespace :admin do
    resources :stack_states, except: [:destroy] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :orders, except: [:destroy] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      # get '/clone', action: 'clone'
      get '/history', action: 'history'
      get '/edition', action: 'edition'
      get '/search_order', action: :search_order, on: :collection, as: 'search_order'
      post '/create_report', action: :create_report, on: :collection, as: 'create_report'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    # resources :orders do

    #   get '(page/:page)', action: :index, on: :collection, as: ''
    #   get '/clone', action: 'clone'
    #   # get '/view_data', action: 'view_data'
    #   # get '/report', action: :report, on: :collection, as: 'report'
    #   # post '/create_report', action: :create_report, on: :collection, as: 'create_report'
    #   delete(
    #     action: :destroy_multiple,
    #     on: :collection,
    #     as: :destroy_multiple
    #   )
    # end

    resources :tasks, except: [:destroy] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :phases, except: [:destroy] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :projects, except: [:destroy] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :customizes do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/install_default', action: 'install_default'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    root to: 'admin#root'

    resources :users, except: [:destroy] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_adwords do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_analytics_tracks do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
        put '/:config/appearance_default', to: 'settings#appearance_default', as: 'appearance_default'
      end
    end
  end


  #Peticiones AJAX 
  resources :projects
  post 'admin/projects/search', as: 'projects_search'

  resources :phases
  post 'admin/tasks/options', as: 'phases_options'

  resources :orders
  post 'admin/orders/project', as: 'orders_project'
  post 'admin/orders/payment_currency', as: 'orders_payment_currency'

  get "users/pending",to:"app/users#pending", as: :app_users_pending
  get "users/locked",to:"app/users#locked", as: :app_users_locked


  # resources :tasks
  # post 'admin/tasks/dinamic', as: 'tasks_dinamic'
  

  # Errors routes
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard route engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'
end

app/models/order.rb
# Order Model
class Order < ActiveRecord::Base
  include ActivityHistory
  include CloneRecord
  belongs_to :project
  has_many :historyorders
  belongs_to :stack_state
  after_create :order_history
  after_update :order_history
  validate :phase_task,:dates

  validates :name_client,:identification_client,:phone_client,:email_client,:date_start_planned,:date_end_planned,:date_start_real,:date_end_real,:date_notification,:payment_currency,:price_project,:user_responsible,:project_id,:stack_state_id,:cost_project,:date_start_real,:person_contact,:email_contact,:phone_contact,:description, presence: {message: "There are blank fields."}
  

 
  def task=(value)
    @phase = value
  end

   def phase_task
    if self.project != nil
      if self.project.phases == []
        errors.add(:project_id, "Estimado usuario, debe ingresar actividades y sus respectivas tareas") 
      elsif @phase == false
        errors.add(:project_id, "Estimado usuario, le falta una tarea a una actividad") 
      end
    end
  end



  def dates
    if self.date_start_real != nil and self.date_end_real != nil and self.date_start_planned != nil and self.date_end_planned != nil
        self.date_start_real = (Date.parse (self.date_start_real.strftime("%d-%m-%Y")))
        self.date_end_real = (Date.parse (self.date_end_real.strftime("%d-%m-%Y")))
        self.date_start_planned = (Date.parse (self.date_start_planned.strftime("%d-%m-%Y")))
        self.date_end_planned = (Date.parse (self.date_end_planned.strftime("%d-%m-%Y")))
        if (Date.parse (self.date_start_real.strftime("%d-%m-%Y"))) > (Date.parse (self.date_start_planned.strftime("%d-%m-%Y")))
          errors.add(:date_start_planned,"estimado usuario la fecha inicial plannifica no puede ser menor a la fecha inicial real#{self.date_start_real}")
        end

        if (Date.parse (self.date_end_real.strftime("%d-%m-%Y"))) < (Date.parse (self.date_end_planned.strftime("%d-%m-%Y")))
          errors.add(:date_end_planned,"estimado usuario la fecha final real no puede ser mayor a la fecha final planificada#{self.date_end_real}")
        end
       
    end
  end



  def order_history
    Historyorder.create(name_client:self.name_client, identification_client:self.identification_client, phone_client:self.phone_client, email_client:self.email_client, date_start_planned:self.date_start_planned,
   date_start_real:self.date_start_real, date_end_planned:self.date_end_planned, date_end_real:self.date_end_real,date_notification:self.date_notification, date_pause:self.date_pause, payment_currency:self.payment_currency, 
   price_project:self.price_project, project_id:self.project_id, order_id:self.id, user_responsible:self.user_responsible, stack_state_id:self.stack_state_id,description:self.description,observation:self.observation)
  end

  # Fields for the search form in the navbar
  def self.search_field
    :name_client_cont
  end
  def redirect(object, commit)
      if commit.key?('_save')
        @order.update(order_params)
        redirect_to admin_order_path(object), notice: actions_messages(object)
      elsif commit.key?('_add_other')
        redirect_to new_admin_order_path, notice: actions_messages(object)
      elsif commit.key?('_assing_rol')
        redirect_to admin_orders_path, notice: actions_messages(object)
      end
    end
end

app/controllers/admin/orders_controller.rb
module Admin
  # OrdersController
  class OrdersController < AdminController
    before_action :set_order, only: [:show, :edit, :update, :destroy]
    before_action :show_history, only: [:index]
    before_action :phase_task_controller
    # GET /orders
    def index
      @q = Order.ransack(params[:q])
      orders = @q.result(distinct: true)
      @objects = orders.page(@current_page)
      @total = orders.size
      if !@objects.first_page? && @objects.size.zero?
        redirect_to orders_path(page: @current_page.to_i.pred, search: @query)
      end
    end

    # GET /orders/1
    def show

    end

    def phase_task_controller
    end
   
    def history
      @order = Order.find(params[:order_id])
      @projects = Project.all
      @phases = Phase.all
      respond_to do |format|
        format.html
        format.json
        format.pdf {render template: 'admin/orders/history_pdf', pdf: 'Report_orders', 
        tamaño_página: 'A4', font_size: '10px', layout: false, margin: {left: 0 , right: 0}  }
      end
    end

    def edition
      @order = Order.find(params[:order_id])
    end

    #Peticiones AJAX
    def project
      @project = Project.find(params[:project_id])
      @@cost_bolivar = 0
      @@cost_dolar = 0
      @@price_bolivar = 0
      @@price_dolar = 0
      @project.phases.each do |phase|
        
        price_bolivar = phase.task.price_bolivar.to_f
        cost_bolivar = phase.task.cost_bolivar.to_f
        price_dolar = phase.task.price_dolar.to_f
        cost_dolar = phase.task.cost_dolar.to_f

        @@price_bolivar = @@price_bolivar + price_bolivar 
        @@cost_bolivar = @@cost_bolivar + cost_bolivar
        @@price_dolar = @@price_dolar + price_dolar 
        @@cost_dolar = @@cost_dolar + cost_dolar
        
     
      
      end
    end   


    def payment_currency
      @payment_currency = (params[:payment_currency])
      @total_price_bolivar = @@price_bolivar 
      @total_cost_bolivar = @@cost_bolivar
      @total_price_dolar = @@price_dolar 
      @total_cost_dolar = @@cost_dolar

      $total_price_bolivar = @@price_bolivar 
      $total_cost_bolivar = @@cost_bolivar
      $total_price_dolar = @@price_dolar 
      $total_cost_dolar = @@cost_dolar

    end 

    def search_order   #report
      @order = Order.new
      respond_to do |format|
         format.html
         format.pdf {render template: 'admin/orders/pdf/report', pdf: 'Report_General',
         tamaño_pagina: 'A4', font_size: '10px', layout: false, margin: {left: 0, right: 0}}
       end
       $bandera = 0
    end

    def create_report
      @@bandera = 0
      $bandera = "1"
      $pdf = $bandera
      @orders = Order.all
      $parametro = @order = Order.new(order_params)
      redirect_to search_order_admin_orders_path
    end
    
    # GET /orders/new
    def new
      @type_money = {}
      @order = Order.new
      @stack_client_name = Premium::Client.all.map {|obj| obj.nombre}
      @tasks = Task.all
      @Projects = Project.all
      @type_money = {USD:'1', VEF:'2'} 

    end

    # GET /orders/1/edit
    def edit
      @stack_states = StackState.all
    end

    # POST /orders
    def create
      
      @order = Order.new(order_params)
      @order.user_responsible = current_user.name
      @stack_state = StackState.all
      @order.stack_state_id = @stack_state = '1'
      if @order.payment_currency == "1"
        @order.price_project = $total_price_dolar
        @order.cost_project = $total_cost_dolar
      elsif @order.payment_currency == "2"
        @order.price_project = $total_price_bolivar
        @order.cost_project = $total_cost_bolivar
      end
      if @order.project != nil
        if @order.project.phases != []
          @order.project.phases.each do |phase|
            if phase.task == nil
              @order.task = (false)
            end
          end
        end
      end
      if @order.save
        redirect(@order, params)
      else
        render :new
      end
    end

    # PATCH/PUT /orders/1
    def update
      if @order.update(order_params)
        redirect(@order, params)
       if @order.project != nil
         if @order.project.phases != []
           @order.project.phases.each do |phase|
             if phase.task == nil
               @order.task = (false)
             end
           end
         end
       end
      else
        render :edit
      end
    end

    def clone
      @order = Order.clone_record params[:order_id]

      if @order.save
        redirect_to admin_orders_path
      else
        render :new
      end
    end

    # DELETE /orders/1
    def destroy
      @order.destroy
      redirect_to admin_orders_path, notice: actions_messages(@order)
    end

    def destroy_multiple
      Order.destroy redefine_ids(params[:multiple_ids])
      redirect_to(
        admin_orders_path(page: @current_page, search: @query),
        notice: actions_messages(Order.new)
      )
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def order_params
      params.require(:order).permit(:name_client, :identification_client, :phone_client, :email_client, :date_start_planned, :date_start_real, :date_end_planned, :date_end_real, :date_pause,:date_notification, :stack_state_id, :payment_currency, :price_project,:cost_project,:description, :observation, :cost_project, :person_contact, :email_contact, :phone_contact,:project_id)
    end

    def show_history
      get_history(Order)
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to admin_orders_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				.card-content
					= simple_form_for [:admin, @order] do |f|
						.row
							= f.association :project, label: false,  label_method: :name, value_method: :id, include_blank: 'Select Project', input_html: { class: "browser-default",  style:"margin-bottom: 5px;" }
							= f.input :name_client, label: 'Name client'
							= f.input :identification_client, label: 'Identification client'
							= f.input :phone_client, label: 'Phone'
							= f.input :email_client, label: 'Email'
							.col.s5{style:"padding: 0px"} 
								= f.input :payment_currency, collection: @type_money, label: false, include_blank: 'Select Payment Currency', input_html: { class: "browser-default", style:"margin-bottom: 5px;" }    
							.col.s2{style:"padding: 0px"}
								.div#money-title{class:"input-field col s12 optional", style:"padding: 0px"}
									%span{style:"text-transform: uppercase; font-weight: bold;"} Cost / Price   
							.col.s5
								.div#money{class:"input-field col s12 optional", style:"padding: 0px"}
									#payment_currency
							#price
							= f.input :date_start_real, label:'Date start real', as: :string, input_html: {class: "datepicker"}
							= f.input :date_end_real, label:'Date end real', as: :string, input_html: {class: "datepicker"}
							= f.input :date_start_planned, label:'Date start planned', as: :string, input_html: {class: "datepicker"}
							= f.input :date_end_planned, label:'Date end planned', as: :string, input_html: {class: "datepicker"}
							-if (controller_name != "orders" and action_name != "new") or (controller_name != "orders" and action_name != "edit")
								= f.input :date_pause, as: :string, input_html: {class: "datepicker"}
							= f.input :date_notification, as: :string, input_html: {class: "datepicker"}
							= f.input :person_contact, label: 'Person Contact'
							= f.input :email_contact, label: 'Phone Contact'
							= f.input :phone_contact, label: 'Email Contact', input_html: {type: "number"}
							= f.input :description

							
							.form-actions.right
								= f.button :submit, t("keppler.actions.save"), name: '_save'
								= f.button :submit, t("keppler.actions.save_and_add_another"), name: '_add_other'
						   
							

   


:javascript

	  $(document).ready(function() {
		$('#order_project_id').on('change', function() {
			$.ajax({
				url: "#{orders_project_path}",
				type: "POST",
				data: { project_id: $(this).val() }
			});
		});

			$('#order_payment_currency').on('change', function() {
			$.ajax({
				url: "#{orders_payment_currency_path}",
				type: "POST",
				data: { payment_currency: $(this).val() }
			});
		});
		$('select').material_select();
		$('.datepicker').pickadate ({
		   min: new Date(),
		   selectMonths: true,
		   yearSelector: false,
		   hiddenName: true,
		   selectYears: 1,
		   editable: false,
		   firstDay: 1,
		   format: 'dd/mm/yyyy',
		   formatSubmit: 'yyyy-mm-dd',
			
	   });

	 // Validacion de fecha comienzo real vs fecha de finalizacion real
	var inicio = $('#order_date_start_real').pickadate(),
	inicio_picker = inicio.pickadate('picker')
	var final = $('#order_date_end_real').pickadate(),
	final_picker = final.pickadate('picker')

	// Check if there’s a “from” or “to” date to start with.
	if (inicio_picker.get('value')) {
	 final_picker.set('min', inicio_picker.get('select'))
	}
	if (final_picker.get('value')) {
	 inicio_picker.set('max', final_picker.get('select'))
	}
	// When something is selected, update the “from” and “to” limits.
	inicio_picker.on('set', function(event) {
	 if (event.select) {
	  final_picker.set('min', inicio_picker.get('select'))
	 } else if ('clear' in event) {
	  final_picker.set('min', false)
	 }
	})
	final_picker.on('set', function(event) {
	 if (event.select) {
	  inicio_picker.set('max', final_picker.get('select'))
	 } else if ('clear' in event) {
	  inicio_picker.set('max', false)
	 }
	})


	});

app/views/admin/orders/_index_show.html.haml
.listing-show-header
	.actions
		= link_to "#modal-#{@order.id}", class: "btn-floating waves-effect waves-light btn-flat tooltipped modal-trigger", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.change_rol")  do
			= material_icon.md_24.supervisor_account
		- if can? :update, Order
			= link_to edit_admin_order_path(@order), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.edit") do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("keppler.models.singularize.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.card-content
		%ul.list
			%li.list-row
				.display-label= t("activerecord.attributes.order.name_client")
				.display-value= @order.name_client
			%li.list-row
				= link_to t('keppler.actions.back_history'), admin_orders_path

= render "admin/orders/modal"
:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/admin/orders/_payment_currency.html.erb
<div id="payment_currency">
	<%if payment_currency == "1"%>
		<span><%="#{@total_cost_dolar} $"%> / <%="#{@total_price_dolar} $"%></span> 
	<%elsif payment_currency == "2"%>
	   <span><%="#{@total_cost_bolivar} Bs.F"%> / <%="#{@total_price_bolivar} Bs.F"%></span>
	<%end%>
</div>

app/views/admin/orders/_project.html.erb
<div id="price">
    <%=@payment_currency%>
</div>

app/views/admin/orders/edit.html.haml
= title(t('keppler.titles.edit', model: "Orders"))
= render 'form'

app/views/admin/orders/edition.html.haml
.wrapper
	.wrapper-body.container
		.actions
		= link_to admin_orders_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
			= material_icon.md_18.arrow_back.css_class("md-dark")
			
		= link_to request.original_url+'.pdf', class: "btn-floating right btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
			= material_icon.md_18.description.css_class("md-dark")	
		.card
			.card-content
				%ul.list
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.id")
						.display-value.fs-body-1.tc-black-2= @order.id.to_s.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.name_client")
						.display-value.fs-body-1.tc-black-2= @order.name_client.to_s.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.identification_client")
						.display-value.fs-body-1.tc-black-2= @order.identification_client.to_s.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.phone_client")
						.display-value.fs-body-1.tc-black-2= @order.phone_client.to_s.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.email_client")
						.display-value.fs-body-1.tc-black-2= @order.email_client.to_s.humanize
					
					%table.responsive-table
						%thead
							%tr
								%th Number Edition
								%th State
								%th Date Start Real
								%th Date Start Planned
								%th Date End Real
								%th Date End Planned
								%th Observation
						%tbody
							-cont = 0
							-@order.historyorders.each do |history_order|
								%tr
									%td
										=cont
									%td
										=history_order.stack_state_id
									%td
										=history_order.date_start_real
									%td
										=history_order.date_start_planned
									%td
										=history_order.date_end_real
									%td
										=history_order.date_end_planned
									%td
										=history_order.observation
								-cont = cont+1
								
									

app/views/admin/orders/h_listing.html.haml
%tr{ id: "row-#{order.id}" }
	- if can? :destroy_multiple, Order
		%td.item-check{style:"width: 10%"}
			= link_to "", admin_order_path(order), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{order.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{order.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{order.id}" }

	%td{style:"width: 30%"}
		= link_to "", admin_order_path(order, search: @query), remote: true, class: "show-row"
		%span
			= order.name_client
	%td{style:"width: 30%"}
		= link_to "", admin_order_path(order, search: @query), remote: true, class: "show-row"
		%span
			= order.identification_client
	%td{style:"width: 30%"}
		= link_to "", admin_order_path(order, search: @query), remote: true, class: "show-row"
		%span
			= order.phone_client
	%td{style:"width: 30%"}
		= link_to "", admin_order_path(order, search: @query), remote: true, class: "show-row"
		%span
			= order.email_client
	%td{style:"width: 30%"}
		= link_to "", admin_order_path(order, search: @query), remote: true, class: "show-row"
		%span
			= order.date_start_planned
	%td{style:"width: 30%"}
		= link_to "", admin_order_path(order, search: @query), remote: true, class: "show-row"
		%span
			= order.date_start_real
	%td{style:"width: 30%"}
		= link_to "", admin_order_path(order, search: @query), remote: true, class: "show-row"
		%span
			= order.date_end_planned
	%td{style:"width: 30%"}
		= link_to "", admin_order_path(order, search: @query), remote: true, class: "show-row"
		%span
			= order.date_end_real
	%td{style:"width: 30%"}
		= link_to "", admin_order_path(order, search: @query), remote: true, class: "show-row"
		%span
			= order.date_pause
	%td{style:"width: 30%"}
		= link_to "", admin_order_path(order, search: @query), remote: true, class: "show-row"
		%span
			= order.state.name
	%td{style:"width: 30%"}
		= link_to "", admin_order_path(order, search: @query), remote: true, class: "show-row"
		%span
			= order.payment_currency
	%td{style:"width: 30%"}
		= link_to "", admin_order_path(order, search: @query), remote: true, class: "show-row"
		%span
			= order.price_project
	%td{style:"width: 30%"}
		= link_to "", admin_order_path(order, search: @query), remote: true, class: "show-row"
		%span
			= order.project_id
	- if can? :clone, Order
		%td{style:"width: 5%"}
			= link_to admin_order_clone_path(order), class: "btn-floating waves-effect btn-flat" do
				= material_icon.md_24.content_copy.css_class("md-dark")
	%td{style:"width: 5%"}
		= link_to admin_order_path(order), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/admin/orders/index.html.haml
= title(t('keppler.titles.index', model: "Orders"))
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_admin_order_path, class: "btn-floating btn-large waves-effect waves-light btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |order|
				= render 'listing', order: order
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t('keppler.messages.not_found_records', model:  t("keppler.models.pluralize.orders"))
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_admin_order_path, class: "btn-index-add btn-floating btn-large waves-effect waves-light" do
		= material_icon.md_24.add.css_class("md-light")
		
:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/admin/orders/new.html.haml
= title(t('keppler.titles.new', model: "Orders"))
= render 'form'

app/views/admin/orders/payment_currency.js.erb
$('#payment_currency').html("<%= j render 'admin/orders/payment_currency', payment_currency: @payment_currency %>")

app/views/admin/orders/project.js.erb
$('#price').html("<%= j render 'admin/orders/project', project: @project %>")