config/routes.rb
Rails.application.routes.draw do
  get '/index', to: 'app/front#index', as: :app_index
  root to: 'app/front#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  namespace :admin do
    resources :stack_states, except: [:destroy] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :orders, except: [:destroy] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      # get '/clone', action: 'clone'
      get '/history', action: 'history'
      get '/edition', action: 'edition'
      get '/search_order', action: :search_order, on: :collection, as: 'search_order'
      post '/create_report', action: :create_report, on: :collection, as: 'create_report'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    # resources :orders do

    #   get '(page/:page)', action: :index, on: :collection, as: ''
    #   get '/clone', action: 'clone'
    #   # get '/view_data', action: 'view_data'
    #   # get '/report', action: :report, on: :collection, as: 'report'
    #   # post '/create_report', action: :create_report, on: :collection, as: 'create_report'
    #   delete(
    #     action: :destroy_multiple,
    #     on: :collection,
    #     as: :destroy_multiple
    #   )
    # end

    resources :tasks, except: [:destroy] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :phases, except: [:destroy] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :projects, except: [:destroy] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :customizes do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/install_default', action: 'install_default'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    root to: 'admin#root'

    resources :users, except: [:destroy] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_adwords do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_analytics_tracks do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
        put '/:config/appearance_default', to: 'settings#appearance_default', as: 'appearance_default'
      end
    end
  end


  #Peticiones AJAX 
  resources :projects
  post 'admin/projects/search', as: 'projects_search'

  resources :phases
  post 'admin/tasks/options', as: 'phases_options'

  resources :orders
  post 'admin/orders/project', as: 'orders_project'
  post 'admin/orders/payment_currency', as: 'orders_payment_currency'

  get "users/pending",to:"app/users#pending", as: :app_users_pending
  get "users/locked",to:"app/users#locked", as: :app_users_locked


  # resources :tasks
  # post 'admin/tasks/dinamic', as: 'tasks_dinamic'
  

  # Errors routes
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard route engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'
end

app/models/project.rb
# Project Model
class Project < ActiveRecord::Base
  include ActivityHistory
  include CloneRecord
  has_many :phases
  has_many :orders
  has_many :tasks
 

  #Field Validation
  validates :name, presence: :true
  validates :name, uniqueness: { message: "El nombre ya se encuentra registrado" }

  
  # Fields for the search form in the navbar
  def self.search_field
    :name_or_group_cont
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  # ProjectsController
  class ProjectsController < AdminController
    before_action :set_project, only: [:show, :edit, :update, :destroy]
    before_action :show_history, only: [:index]
    #person
    before_action :premium

    def premium
       @list_project_name = Premium::Article.all.map {|obj| obj.nombre}
    end

    # GET /projects
    def index
      @q = Project.ransack(params[:q])
      projects = @q.result(distinct: true)
      @objects = projects.page(@current_page)
      @total = projects.size
      if !@objects.first_page? && @objects.size.zero?
        redirect_to projects_path(page: @current_page.to_i.pred, search: @query)
      end
    end

    # GET /projects/1
    def show
    end

    # GET /projects/new
    def new
      @project = Project.new  
      #@list_project_name = Premium::Article.all.map {|obj| obj.nombre}
    end

    # GET /projects/1/edit
    def edit

      #@list_project_name = Premium::Article.all.map {|obj| obj.nombre}
    end

    # POST /projects
    def create
      @project = Project.new(project_params)
      @stack_product=Premium::Article.all
      @stack_product.each do |articulo|
        if @project.name == articulo.nombre
           @project.group = articulo.grupo
        else
          puts "¡Error! create"
        end
      end
      
      if @project.save
        redirect(@project, params)
      else
        render :new
      end
    end

    # PATCH/PUT /projects/1
    def update
      if @project.update(project_params)
        redirect(@project, params)
        @stack_product=Premium::Article.all
        @stack_product.each do |articulo|
          if @project.name == articulo.nombre
             @project.group = articulo.grupo
             @project.save

          end
        end
      else
        render :edit
      end
    end

    def clone
      @project = Project.clone_record params[:project_id]
      if @project.save
        redirect_to admin_projects_path
      else
        render :new
      end
    end

    # DELETE /projects/1
    def destroy
      @project.destroy
      redirect_to admin_projects_path, notice: actions_messages(@project)
    end

    def destroy_multiple
      Project.destroy redefine_ids(params[:multiple_ids])
      redirect_to(
        admin_projects_path(page: @current_page, search: @query),
        notice: actions_messages(Project.new)
      )
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:name,:group)
    end

    def show_history
      get_history(Project)
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to admin_projects_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				.card-content
					= simple_form_for [:admin, @project] do |f|
						.row
							= f.input :name, collection: @list_project_name, label: false,include_blank: 'Select Project', input_html: { class: "browser-default",  style:"margin-bottom: 5px;" }
							.form-actions.right
								= f.button :submit, t("keppler.actions.save"), name: '_save'
								= f.button :submit, t("keppler.actions.save_and_add_another"), name: '_add_other'

app/views/admin/projects/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Project
			= link_to edit_admin_project_path(@project), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.edit") do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("keppler.models.singularize.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.card-content
		%ul.list
			%li.list-row
				.display-label= t("activerecord.attributes.project.name")
				.display-value= @project.name
			%li.list-row
				.display-label= t("activerecord.attributes.project.group")
				.display-value= @project.group
			%li.list-row
				= link_to t('keppler.actions.back_history'), admin_projects_path

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/admin/projects/_listing.html.haml
%tr{ id: "row-#{project.id}" }
	-# - if can? :destroy_multiple, Project
	-#  %td.item-check{style:"width: 10%"}
	-#      = link_to "", admin_project_path(project), remote: true, class: "show-row"
	-#      %input{ type:"checkbox", class: "filled-in", id: "checkbox-#{project.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{project.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
	-#      %label{ for: "checkbox-#{project.id}" }
	%td{style:"width: 2%"}
	%td{style:"width: 20%"}
		= link_to "", admin_project_path(project, search: @query), remote: true, class: "show-row"
		%span
			= project.name
	%td{style:"width: 10%"}
		= link_to "", admin_project_path(project, search: @query), remote: true, class: "show-row"
		%span
			= project.id
	%td{style:"width: 10%"}
		= link_to "", admin_project_path(project, search: @query), remote: true, class: "show-row"
		%span
			= project.group
	-# - if can? :clone, Project
	-#  %td{style:"width: 5%"}
			-# = link_to admin_project_clone_path(project), class: "btn-floating waves-effect btn-flat" do
			-#  = material_icon.md_24.search.css_class("md-dark")
	%td{style:"width: 6%"}
		= link_to admin_project_path(project), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.visibility.css_class("md-dark")

app/views/admin/projects/edit.html.haml
= title(t('keppler.titles.edit', model: "Projects"))
= render 'form'

app/views/admin/projects/index.html.haml
= title(t('keppler.titles.index', model: "Projects"))
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_admin_project_path, class: "btn-floating btn-large waves-effect waves-light btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |project|
				= render 'listing', project: project
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t('keppler.messages.not_found_records', model:  t("keppler.models.pluralize.projects"))
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_admin_project_path, class: "btn-index-add btn-floating btn-large waves-effect waves-light" do
		= material_icon.md_24.add.css_class("md-light")

app/views/admin/projects/new.html.haml
= title(t('keppler.titles.new', model: "Projects"))
= render 'form'

app/views/admin/projects/show.html.haml
= title(t('keppler.titles.show', model: "Projects"))
.wrapper
	.wrapper-body.container
		.actions
			-# - if can? :delete, Project
			-# 	= link_to admin_project_path(@project), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.delete"), method: :delete, data: { confirm: t("keppler.messages.data_confirm") } do
			-# 		= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, Project
				= link_to edit_admin_project_path(@project), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" =>t("keppler.actions.edit") do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to admin_projects_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			.card-content
				%ul.list
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.id")
						.display-value.fs-body-1.tc-black-2= @project.id.to_s.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.name")
						.display-value.fs-body-1.tc-black-2= @project.name.to_s.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.group")
						.display-value.fs-body-1.tc-black-2= @project.group.to_s.humanize

app/views/admin/projects/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@project.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");